name: CI

on: workflow_dispatch

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - run: |
        echo ${{ github.workspace }}
        echo $GITHUB_WORKSPACE

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v6
      with:
        python-version: 3.12

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Clean Data
      run: |
        echo "Cleaning data..."
        pwd
        ls -al
        cd ModelCleaning
        pip install pandas
        python Cleandata.py
        ls -al

    - name: Train and Test Model
      run: |
        echo "Training and testing model..."
        pip install scikit-learn joblib
        python ModelCleaning/train_test_dataset.py